name: CI/CD

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal  

      - name: Install coverlet
        run: dotnet tool install --global coverlet.console

      - name: Run automated unit and integration tests
        run: dotnet test MyProClip_UnitTest/MyProClip_UnitTest.csproj /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: Publish coverage report to coveralls.io   
        uses: coverallsapp/github-action@master   
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }} 
          path-to-lcov: MyProClip_UnitTest/TestResults/coverage.info 

      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: ./MyProClip.sln
          minimumSeverity: error

      - name: Buildx docker
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mypro144/myproclip:latest
          
  deploy_locally:
    name: Deploy Locally
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull mypro144/myproclip:latest
        
      - name: Run Docker container
        run: docker run -d --network myproclip_network -p 32769:8080 -p 8000:8081 --name MyProClip_Prod -e ASPNETCORE_ENVIRONMENT=Development mypro144/myproclip:latest 
