name: CI/CD

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal  

      - name: Install ReSharper CLT
        run: |
          wget -O inspectcode.zip https://download.jetbrains.com/resharper/ReSharper.CommandLineTools.zip
          unzip inspectcode.zip -d inspectcode
      - name: Run ReSharper Analysis
        run: ./inspectcode/inspectcode.sh MyProClip.sln --output=resharper_analysis_results.xml

      - name: Process Analysis Results
        run: |
          if grep -q '<Issue Severity="ERROR"' resharper_analysis_results.xml; then
            echo "Critical issues found. Failing build."
            exit 1
          fi

      - name: Buildx docker
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mypro144/myproclip:latest
