name: .NET build and tests

on:
  pull_request:
    branches: [ "master", "develop" ]
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Install ReSharper CLT
      run: |
        wget -O inspectcode.zip https://download.jetbrains.com/resharper/ReSharper.CommandLineTools.zip
        unzip inspectcode.zip -d inspectcode
    - name: Run ReSharper Analysis
      run: ./inspectcode/inspectcode.sh MyProClip.sln --output=resharper_analysis_results.xml

    - name: Process Analysis Results
      run: |
        if grep -q '<Issue Severity="ERROR"' resharper_analysis_results.xml; then
          echo "Critical issues found. Failing build."
          exit 1
        fi
